name: apache-wayang2

services:
  app:
    container_name: apache-wayang-appJA
    image: apache/incubator-wayang:latest
    ports:
      - 8888:8888
    volumes:
      - ./:/var/www/html
      - ./.m2/repository/:/root/.m2/repository
    tty: true
    restart: always